### ISSUE TITLE
Disqus latest discussions showing a UUID, instead of title of the post

### ISSUE THREAD

**Issue by fr0der1c** [QardsJs/qards#84]
On disqus (https://disqus.com/home/forums/admirable-blog/), there is a UUID of each activity instead of the title of the post. Is this related to Qards?

![image](https://user-images.githubusercontent.com/16500161/50545329-bbd62e80-0c4a-11e9-95f3-0bb1d72f8159.png)

**Comment by ciokan** [comment]
didn't find that id in the article:

`curl https://blog.admirable.pro/sentry-sdk-cause-segmentation-fault/ | grep b7e19bb5-7071-55fe-9c31-500b2fb7ef84`

**Comment by fr0der1c** [comment]
Yeah, it's not a part of the article itself. I think the problem is related to the Disqus integration of Qards. Maybe Disqus requires a title to be passed but Qards is not passing one, so Disqus just generated a UUID?

**Comment by ciokan** [comment]
Will have a look. Thanks!

**Comment by ciokan** [comment]
Fixed via: https://github.com/QardsJs/qards/commit/7b866603278fadc41d2d8a5b07eaf84e75a270aa

I pushed some cleanups lately so make sure you don't use any of the images that were uploaded with qards by default (upload your own). This includes user avatar, images in posts, galleries...any picture that you used and wasn't uploaded by you.

**Comment by fr0der1c** [comment]
Thanks for the notice!

**Comment by fr0der1c** [comment]
I pull the latest commit and seems the problem persists.

![image](https://user-images.githubusercontent.com/16500161/50555128-e4b9fa80-0d02-11e9-88fd-b120dd8f447d.png)

**Comment by ciokan** [comment]
Could it be that they cached the results? In the commit you can see the mistake I made but I don't know how would they grab the id now...

**Comment by fr0der1c** [comment]
Maybe the title won't be updated anyway. I tried a new article and it works fine. But for articles already in Disqus, no.

**Comment by ciokan** [comment]
So it's safe to close this issue now?

**Comment by fr0der1c** [comment]
Yes. Looks good to me.
